### ISSUE TITLE
关于第十二课 mydocker stop

### ISSUE THREAD

**Issue by Chen-Litao** [lixd/mydocker#3]
请问一下第十二课中
`// 2.发送SIGTERM信号
	if err = syscall.Kill(pidInt, syscall.SIGTERM); err != nil {
		log.Errorf("Stop container %s error %v", containerId, err)
		return
	}`
syscall.SIGTERM换成syscall.SIGTERM是否更合适一点呢

**Comment by Chen-Litao** [comment]
换成syscall.SIGSTOP

**Comment by lixd** [comment]
是的，kill 有点粗暴了哈哈，我改一下子

**Comment by lixd** [comment]
看了一下代码，感觉是弄错了，我以为是直接 SIGKILL 呢, 现在用的 SIGTERM 是 ok 的。
几个 signal 的区别：
```bash
SIGKILL kills a process and cannot be caught

SIGTERM kills a process but can be caught to do a graceful exit

SIGSTOP suspends the process until you do a SIGCONT
```
然后 Docker 的描述
* docker stop: Stop a running container (send SIGTERM, and then SIGKILL after grace period) [...] The main process inside the container will receive SIGTERM, and after a grace period, SIGKILL. [emphasis mine]
* docker kill: Kill a running container (send SIGKILL, or specified signal) [...] The main process inside the container will be sent SIGKILL, or any signal specified with option --signal. [emphasis mine]

docker stop 就是停止容器，不是暂停容器，因此不是用的 SIGSTOP

**Comment by Chen-Litao** [comment]
好的好的，感谢回复
